/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package orientacaoexame;

import javax.swing.JOptionPane;

/**
 *
 * @author Giulianno
 */
public class FormCRUDExames extends javax.swing.JFrame {

    /**
     * Creates new form FormCRUDExames
     */
    public FormCRUDExames() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ftfPrazoEntrega = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cbAgendamento = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cbAutorizacao = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        cbAtivo = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        tfObservacoes = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        btCadastrarExame = new javax.swing.JButton();
        btCancelarExame = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(7, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Exame");
        getContentPane().add(jLabel1);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        jLabel2.setText("Nome:");
        jPanel1.add(jLabel2);

        tfNome.setColumns(40);
        jPanel1.add(tfNome);

        getContentPane().add(jPanel1);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        jLabel3.setText("Código:");
        jPanel2.add(jLabel3);

        tfCodigo.setColumns(15);
        tfCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCodigoActionPerformed(evt);
            }
        });
        jPanel2.add(tfCodigo);

        jLabel4.setText("Prazo de Entrega:");
        jPanel2.add(jLabel4);

        ftfPrazoEntrega.setColumns(15);
        ftfPrazoEntrega.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        ftfPrazoEntrega.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(ftfPrazoEntrega);

        getContentPane().add(jPanel2);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        jLabel5.setText("Agendamento:");
        jPanel3.add(jLabel5);

        cbAgendamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Sim", "Não" }));
        jPanel3.add(cbAgendamento);

        jLabel6.setText("                Tipo de Exame: ");
        jPanel3.add(jLabel6);

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Laboratório", "Imagem" }));
        jPanel3.add(cbTipo);

        getContentPane().add(jPanel3);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        jLabel7.setText("Autorização:   ");
        jPanel4.add(jLabel7);

        cbAutorizacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Sim", "Não" }));
        jPanel4.add(cbAutorizacao);

        jLabel8.setText("                Ativo:");
        jPanel4.add(jLabel8);

        cbAtivo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Sim", "Não" }));
        jPanel4.add(cbAtivo);

        getContentPane().add(jPanel4);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        jLabel9.setText("Observações: ");
        jPanel5.add(jLabel9);

        tfObservacoes.setColumns(35);
        tfObservacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfObservacoesActionPerformed(evt);
            }
        });
        jPanel5.add(tfObservacoes);

        getContentPane().add(jPanel5);

        btCadastrarExame.setText("Cadastrar");
        btCadastrarExame.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btCadastrarExame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCadastrarExameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btCadastrarExameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btCadastrarExameMouseExited(evt);
            }
        });
        btCadastrarExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarExameActionPerformed(evt);
            }
        });
        jPanel6.add(btCadastrarExame);

        btCancelarExame.setText("Cancelar");
        btCancelarExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarExameActionPerformed(evt);
            }
        });
        jPanel6.add(btCancelarExame);

        getContentPane().add(jPanel6);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCodigoActionPerformed

    private void btCadastrarExameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCadastrarExameMouseEntered
        // TODO add your handling code here:
        btCadastrarExame.setText("Cadastra Exame!");
    }//GEN-LAST:event_btCadastrarExameMouseEntered

    private void btCadastrarExameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCadastrarExameMouseExited
        // TODO add your handling code here:
        btCadastrarExame.setText("Cadastrar");
    }//GEN-LAST:event_btCadastrarExameMouseExited

    private void btCadastrarExameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCadastrarExameMouseClicked
        // TODO add your handling code here:
        exame = new Exame();
        exame.criarExame(tfNome.getText(), tfCodigo.getText(), cbAgendamento.getSelectedItem().toString(), cbAutorizacao.getSelectedItem().toString(), cbAtivo.getSelectedItem().toString(), tfObservacoes.getText(), ftfPrazoEntrega.getText());
        JOptionPane.showMessageDialog(null, "Exame Cadastrado!");
    }//GEN-LAST:event_btCadastrarExameMouseClicked

    private void tfObservacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfObservacoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfObservacoesActionPerformed

    private void btCancelarExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarExameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCancelarExameActionPerformed

    private void btCadastrarExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarExameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCadastrarExameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCRUDExames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCRUDExames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCRUDExames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCRUDExames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCRUDExames().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrarExame;
    private javax.swing.JButton btCancelarExame;
    private javax.swing.JComboBox cbAgendamento;
    private javax.swing.JComboBox cbAtivo;
    private javax.swing.JComboBox cbAutorizacao;
    private javax.swing.JComboBox cbTipo;
    private javax.swing.JFormattedTextField ftfPrazoEntrega;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfObservacoes;
    // End of variables declaration//GEN-END:variables

    Exame exame = null;
}
