/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package videolocadora;

/**
 *
 * @author Giulianno
 */
public class FormConsultaFilme extends javax.swing.JFrame {

    private Filme filme;
    /**
     * Creates new form FormConsultaFilme
     */
    public FormConsultaFilme(Filme filme) {
        this.filme = filme;
        
        initComponents();
        this.setSize(300, 300);
        this.setResizable(false);
        this.setVisible(true);
    }
    
    public void atualizaCampos() {
        lbTituloFilme.setText(filme.getTitulo());
        lbDiretorFilme.setText(filme.getDiretor());
        lbGeneroFilme.setText(filme.getGenero());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbTituloFilme = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbDiretorFilme = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lbGeneroFilme = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(4, 1));

        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("Consulta Filme");
        getContentPane().add(lbTitulo);

        jPanel1.setLayout(new java.awt.FlowLayout(0));

        jLabel2.setText("Título:");
        jPanel1.add(jLabel2);
        jPanel1.add(lbTituloFilme);

        getContentPane().add(jPanel1);

        jPanel2.setLayout(new java.awt.FlowLayout(0));

        jLabel3.setText("Diretor:");
        jPanel2.add(jLabel3);
        jPanel2.add(lbDiretorFilme);

        getContentPane().add(jPanel2);

        jPanel3.setLayout(new java.awt.FlowLayout(0));

        jLabel4.setText("Gênero:");
        jPanel3.add(jLabel4);
        jPanel3.add(lbGeneroFilme);

        getContentPane().add(jPanel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbDiretorFilme;
    private javax.swing.JLabel lbGeneroFilme;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbTituloFilme;
    // End of variables declaration//GEN-END:variables
}
